In [ ]:
EXAMPLE = 'jan3_2rvn_hide_demand.json'

In [ ]:
!python /apps/open_spiel/open_spiel/python/examples/ubc_example.py --filename {EXAMPLE} --show_obs True --seed 88

In [ ]:
EXAMPLE = 'jan3_2rvn_base.json'
!python /apps/open_spiel/open_spiel/python/examples/ubc_example.py --filename {EXAMPLE} --show_obs True --seed 55

In [22]:
!cat /apps/open_spiel/configs/jan12_2rvn_reveal.json

{"activity": [5, 14, 8], "increment": 0.1, "information_policy": "show_demand", "licenses": [3, 3, 3], "opening_price": [150, 450, 200], "undersell_rule": "undersell", "license_names": ["British Columbia", "Ontario", "Quebec"], "players": [{"type": [{"value": [0, 228, 419, 643, 419, 648, 839, 1062, 680, 909, 1100, 1324, 886, 1115, 1306, 1529, 220, 449, 640, 863, 640, 868, 1060, 1283, 901, 1129, 1321, 1544, 1107, 1335, 1527, 1750, 363, 591, 783, 1006, 783, 1011, 1203, 1426, 1044, 1272, 1464, 1687, 1250, 1478, 1670, 1893, 480, 708, 900, 1123, 900, 1128, 1320, 1543, 1161, 1389, 1581, 1804, 1367, 1595, 1787, 2010], "value_format": "full", "budget": 2010, "prob": 0.3333333333333333, "name": "regional_0"}, {"value": [0, 96, 156, 205, 516, 612, 673, 721, 864, 961, 1021, 1070, 1168, 1265, 1325, 1374, 356, 452, 513, 561, 872, 968, 1029, 1077, 1221, 1317, 1378, 1426, 1524, 1621, 1681, 1730, 642, 738, 799, 847, 1158, 1254, 1315, 1363, 1506, 1603, 1663, 1712, 1810, 1907, 1967, 2016, 958, 1055, 111

In [76]:
EXAMPLE = 'jan12_2rvn_reveal.json'
!python /apps/open_spiel/open_spiel/python/examples/ubc_example.py --filename {EXAMPLE} --show_obs True --seed 555

FIXING SEED 555
I0117 23:31:36.427150 140347751236096 ubc_utils.py:44] Setting numpy and torch seed to 555
Creating game: python_clock_auction
I0117 23:31:36.427884 140347751236096 clock_auction.py:133] Reading from env variable CLOCK_AUCTION_CONFIG_DIR. If it is not set, there will be trouble.
I0117 23:31:36.427969 140347751236096 clock_auction.py:137] CLOCK_AUCTION_CONFIG_DIR=/apps/open_spiel/configs
I0117 23:31:36.428009 140347751236096 clock_auction.py:140] Parsing configuration from /apps/open_spiel/configs/jan12_2rvn_reveal.json
I0117 23:31:36.428508 140347751236096 clock_auction.py:213] Done config parsing
Round: 1

Chance node, got 3 outcomes
Sampled outcome:  Assign player 0 type regional_2
Round: 1
Player 0: regional_2

Chance node, got 3 outcomes
Sampled outcome:  Assign player 1 type regional_0
Round: 1
Player 0: regional_2
Player 1: regional_0

Chance node, got 3 outcomes
Sampled outcome:  Assign player 2 type national_2
Round: 1
Player 0: regional_2
Player 1: regional_0
P

In [70]:
import numpy as np
tiny_history = np.array([
    [1, 0, 1],
])

short_history = np.array([
    [1, 0, 1],
    [2, 1, 0], 
])

medium_history = np.array([
    [1, 0, 1],
    [2, 1, 0], 
    [3, 3, 1],
])

history = np.array([
    [1, 0, 1],
    [2, 1, 0], 
    [3, 3, 1],
    [1, 1, 1],
])





In [4]:
import pyspiel
import open_spiel.python.games
game = pyspiel.load_game('python_clock_auction', dict(filename='jan12_regional_vs_national_base.json')) 
state = game.new_initial_state()


In [48]:
history[-3:]

array([[1, 0, 1],
       [2, 1, 0]])

In [74]:
for h in [tiny_history, short_history, medium_history, history]:
    values = np.zeros((len(state.auction_params.all_bids), 3))
    # print(h[-3:, np.newaxis].shape) # mem x num_products x 1
    # print(state.auction_params.all_bids[np.newaxis, :, :].shape) # 1 x bundles x num_products
    one_hot = np.all(h[-3:, np.newaxis] == state.auction_params.all_bids[np.newaxis, :, :], axis=2).astype(int).T
    values[:, -one_hot.shape[1]:] = one_hot

    print(values)
    print()


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [

In [38]:
for row in history[-3:]:
    x = np.all(row == state.auction_params.all_bids, axis=1).astype(int)
    print(x)
# np.where(history[-3:] == state.auction_params.all_bids)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [22]:
state.auction_params.all_bids

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 3],
       [0, 1, 0],
       [0, 1, 1],
       [0, 1, 2],
       [0, 1, 3],
       [0, 2, 0],
       [0, 2, 1],
       [0, 2, 2],
       [0, 2, 3],
       [0, 3, 0],
       [0, 3, 1],
       [0, 3, 2],
       [0, 3, 3],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 2],
       [1, 0, 3],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 3],
       [1, 2, 0],
       [1, 2, 1],
       [1, 2, 2],
       [1, 2, 3],
       [1, 3, 0],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 3],
       [2, 0, 0],
       [2, 0, 1],
       [2, 0, 2],
       [2, 0, 3],
       [2, 1, 0],
       [2, 1, 1],
       [2, 1, 2],
       [2, 1, 3],
       [2, 2, 0],
       [2, 2, 1],
       [2, 2, 2],
       [2, 2, 3],
       [2, 3, 0],
       [2, 3, 1],
       [2, 3, 2],
       [2, 3, 3],
       [3, 0, 0],
       [3, 0, 1],
       [3, 0, 2],
       [3, 0, 3],
       [3, 1, 0],
       [3, 1, 1],
       [3, 1, 2],
       [3,