In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import types
import pyspiel
import open_spiel.python.games
from open_spiel.python.observation import make_observation
import numpy as np


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [47]:
# game = pyspiel.load_game('python_kuhn_poker')
# state = game.new_initial_state()
# state.apply_action(1)
# state.apply_action(1)
# state.information_state_tensor()

In [48]:
len(state.information_state_tensor())

11

4

In [74]:
# np.array(state.information_state_tensor()).reshape(len(game.auction_params.all_bids), -1, order='F')

In [4]:
np.array(state.information_state_tensor()).reshape(-1, len(game.auction_params.all_bids))

NameError: name 'state' is not defined

In [44]:
game = pyspiel.load_game('python_clock_auction', dict(filename='parameters.json')) 
state = game.new_initial_state()
for action in [0, 0, # Chance
1, 1, # R1 bids 
1, 1, # R2 bids
0, # Chance
2, 1, # R3 bids
0,  # Chance
# # 0,  # Chance
]:
    print(state.current_player())
    if len(state.bidders) >= 1:
        print(state.bidders[0].processed_demand)
    state.apply_action(action)

print("CURRENT PLAYER", state.current_player())
print("ROUND", state.round)
print("TERMINAL", state.is_terminal())
obs = make_observation(game, params={'normalize': False})
obs.set_from(state, player=0)

PlayerId.CHANCE
PlayerId.CHANCE
[array([0, 0])]
0
[array([0, 0])]
1
[array([0, 0])]
0
[array([0, 0]), array([0, 1])]
1
[array([0, 0]), array([0, 1])]
PlayerId.CHANCE
[array([0, 0]), array([0, 1])]
0
[array([0, 0]), array([0, 1]), array([0, 1])]
1
[array([0, 0]), array([0, 1]), array([0, 1])]
PlayerId.CHANCE
[array([0, 0]), array([0, 1]), array([0, 1])]
CURRENT PLAYER PlayerId.TERMINAL
ROUND 3
TERMINAL True


In [45]:
for k in obs.dict:
    print(k, obs.dict[k].shape) 
    print(obs.dict[k])
    print()
# pprint(obs.dict)

my_activity (4,)
[100. 100. 100. 100.]

sor_exposure (4,)
[100. 100. 100. 100.]

amount (2, 4)
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]]

activity (4,)
[  0. 100. 100. 200.]

values (4,)
[  0. 125. 125. 250.]

prev_processed (4,)
[0. 0. 1. 0.]

prev_demanded (4,)
[0. 0. 1. 0.]

submitted_demand_history (3, 4)
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]

processed_demand_history (3, 4)
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]

agg_demand_history (3, 2, 4)
[[[0. 0. 0. 0.]
  [2. 2. 2. 2.]]

 [[0. 0. 0. 0.]
  [2. 2. 2. 2.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

sor_bundle_prices_history (3, 4)
[[  0. 100. 100. 200.]
 [  0. 110. 100. 210.]
 [  0. 121. 100. 221.]]



In [39]:
obs.tensor.reshape(obs.observation_shape)

array([[100., 100., 100., 100.],
       [110., 110., 110., 110.],
       [  0.,   0.,   1.,   1.],
       [  0.,   1.,   0.,   1.],
       [  0., 100., 100., 200.],
       [  0., 125., 125., 250.],
       [  0.,   1.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  2.,   2.,   2.,   2.],
       [  0.,   0.,   0.,   0.],
       [  0., 100., 100., 200.],
       [  0., 110., 100., 210.]], dtype=float32)

In [28]:
for k, _, _, _ in obs.pieces:
    print(k)

my_activity
sor_exposure
amount
activity
values
prev_processed
prev_demanded
submitted_demand_history
processed_demand_history
agg_demand_history
sor_bundle_prices_history


In [92]:
from pprint import pprint

In [6]:
str(state)

'Round: 2\nPlayer 0: LinearValues: [125 125] Budget: 150\nPlayer 1: LinearValues: [  0 150] Budget: 150\nPrice: [100. 110.]\nProcessed Demand:\n[0 1]\n[0 1]\nAggregate demand: [0 2]\n'

In [ ]:
state.information_state_tensor()

In [ ]:
state.observation_tensor()

In [ ]:
state.bidders[0]

In [40]:
x = state.auction_params.all_bids.T 
y= state.auction_params.licenses

In [55]:
x / y[:, None]

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]])